// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package pangea

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageStateChange_NewState int32

const (
	MessageStateChange_SENT             MessageStateChange_NewState = 0
	MessageStateChange_DELIVERED        MessageStateChange_NewState = 1
	MessageStateChange_FAILED_TO_HANDLE MessageStateChange_NewState = 2
)

var MessageStateChange_NewState_name = map[int32]string{
	0: "SENT",
	1: "DELIVERED",
	2: "FAILED_TO_HANDLE",
}
var MessageStateChange_NewState_value = map[string]int32{
	"SENT":             0,
	"DELIVERED":        1,
	"FAILED_TO_HANDLE": 2,
}

func (x MessageStateChange_NewState) String() string {
	return proto.EnumName(MessageStateChange_NewState_name, int32(x))
}
func (MessageStateChange_NewState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{5, 0}
}

type DoubleRatchedMsg struct {
	DoubleRatchetPK      []byte   `protobuf:"bytes,1,opt,name=doubleRatchetPK,proto3" json:"doubleRatchetPK,omitempty"`
	N                    uint32   `protobuf:"varint,2,opt,name=n" json:"n,omitempty"`
	Pn                   uint32   `protobuf:"varint,3,opt,name=pn" json:"pn,omitempty"`
	CipherText           []byte   `protobuf:"bytes,4,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleRatchedMsg) Reset()         { *m = DoubleRatchedMsg{} }
func (m *DoubleRatchedMsg) String() string { return proto.CompactTextString(m) }
func (*DoubleRatchedMsg) ProtoMessage()    {}
func (*DoubleRatchedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{0}
}
func (m *DoubleRatchedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleRatchedMsg.Unmarshal(m, b)
}
func (m *DoubleRatchedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleRatchedMsg.Marshal(b, m, deterministic)
}
func (dst *DoubleRatchedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleRatchedMsg.Merge(dst, src)
}
func (m *DoubleRatchedMsg) XXX_Size() int {
	return xxx_messageInfo_DoubleRatchedMsg.Size(m)
}
func (m *DoubleRatchedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleRatchedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleRatchedMsg proto.InternalMessageInfo

func (m *DoubleRatchedMsg) GetDoubleRatchetPK() []byte {
	if m != nil {
		return m.DoubleRatchetPK
	}
	return nil
}

func (m *DoubleRatchedMsg) GetN() uint32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *DoubleRatchedMsg) GetPn() uint32 {
	if m != nil {
		return m.Pn
	}
	return 0
}

func (m *DoubleRatchedMsg) GetCipherText() []byte {
	if m != nil {
		return m.CipherText
	}
	return nil
}

type PlainChatMessage struct {
	DAppPublicKey            []byte   `protobuf:"bytes,1,opt,name=dAppPublicKey,proto3" json:"dAppPublicKey,omitempty"`
	Type                     string   `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Params                   []byte   `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	Message                  []byte   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt                int64    `protobuf:"varint,5,opt,name=createdAt" json:"createdAt,omitempty"`
	MessageID                string   `protobuf:"bytes,6,opt,name=messageID" json:"messageID,omitempty"`
	SharedSecretBaseID       []byte   `protobuf:"bytes,7,opt,name=sharedSecretBaseID,proto3" json:"sharedSecretBaseID,omitempty"`
	SharedSecretCreationDate int64    `protobuf:"varint,8,opt,name=sharedSecretCreationDate" json:"sharedSecretCreationDate,omitempty"`
	Version                  uint32   `protobuf:"varint,9,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *PlainChatMessage) Reset()         { *m = PlainChatMessage{} }
func (m *PlainChatMessage) String() string { return proto.CompactTextString(m) }
func (*PlainChatMessage) ProtoMessage()    {}
func (*PlainChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{1}
}
func (m *PlainChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlainChatMessage.Unmarshal(m, b)
}
func (m *PlainChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlainChatMessage.Marshal(b, m, deterministic)
}
func (dst *PlainChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlainChatMessage.Merge(dst, src)
}
func (m *PlainChatMessage) XXX_Size() int {
	return xxx_messageInfo_PlainChatMessage.Size(m)
}
func (m *PlainChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PlainChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PlainChatMessage proto.InternalMessageInfo

func (m *PlainChatMessage) GetDAppPublicKey() []byte {
	if m != nil {
		return m.DAppPublicKey
	}
	return nil
}

func (m *PlainChatMessage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PlainChatMessage) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *PlainChatMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PlainChatMessage) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *PlainChatMessage) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *PlainChatMessage) GetSharedSecretBaseID() []byte {
	if m != nil {
		return m.SharedSecretBaseID
	}
	return nil
}

func (m *PlainChatMessage) GetSharedSecretCreationDate() int64 {
	if m != nil {
		return m.SharedSecretCreationDate
	}
	return 0
}

func (m *PlainChatMessage) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type ChatMessage struct {
	OneTimePreKey            []byte            `protobuf:"bytes,1,opt,name=oneTimePreKey,proto3" json:"oneTimePreKey,omitempty"`
	SignedPreKey             []byte            `protobuf:"bytes,2,opt,name=signedPreKey,proto3" json:"signedPreKey,omitempty"`
	EphemeralKey             []byte            `protobuf:"bytes,3,opt,name=ephemeralKey,proto3" json:"ephemeralKey,omitempty"`
	EphemeralKeySignature    []byte            `protobuf:"bytes,4,opt,name=ephemeralKeySignature,proto3" json:"ephemeralKeySignature,omitempty"`
	SenderChatIDKey          []byte            `protobuf:"bytes,5,opt,name=senderChatIDKey,proto3" json:"senderChatIDKey,omitempty"`
	SenderChatIDKeySignature []byte            `protobuf:"bytes,6,opt,name=senderChatIDKeySignature,proto3" json:"senderChatIDKeySignature,omitempty"`
	Message                  *DoubleRatchedMsg `protobuf:"bytes,8,opt,name=message" json:"message,omitempty"`
	Receiver                 []byte            `protobuf:"bytes,9,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender                   []byte            `protobuf:"bytes,10,opt,name=sender,proto3" json:"sender,omitempty"`
	MessageID                []byte            `protobuf:"bytes,11,opt,name=messageID,proto3" json:"messageID,omitempty"`
	UsedSharedSecret         []byte            `protobuf:"bytes,12,opt,name=usedSharedSecret,proto3" json:"usedSharedSecret,omitempty"`
	Version                  uint32            `protobuf:"varint,13,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}          `json:"-"`
	XXX_unrecognized         []byte            `json:"-"`
	XXX_sizecache            int32             `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{2}
}
func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (dst *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(dst, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetOneTimePreKey() []byte {
	if m != nil {
		return m.OneTimePreKey
	}
	return nil
}

func (m *ChatMessage) GetSignedPreKey() []byte {
	if m != nil {
		return m.SignedPreKey
	}
	return nil
}

func (m *ChatMessage) GetEphemeralKey() []byte {
	if m != nil {
		return m.EphemeralKey
	}
	return nil
}

func (m *ChatMessage) GetEphemeralKeySignature() []byte {
	if m != nil {
		return m.EphemeralKeySignature
	}
	return nil
}

func (m *ChatMessage) GetSenderChatIDKey() []byte {
	if m != nil {
		return m.SenderChatIDKey
	}
	return nil
}

func (m *ChatMessage) GetSenderChatIDKeySignature() []byte {
	if m != nil {
		return m.SenderChatIDKeySignature
	}
	return nil
}

func (m *ChatMessage) GetMessage() *DoubleRatchedMsg {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ChatMessage) GetReceiver() []byte {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *ChatMessage) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *ChatMessage) GetMessageID() []byte {
	if m != nil {
		return m.MessageID
	}
	return nil
}

func (m *ChatMessage) GetUsedSharedSecret() []byte {
	if m != nil {
		return m.UsedSharedSecret
	}
	return nil
}

func (m *ChatMessage) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type PreKey struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	IdentityKey          []byte   `protobuf:"bytes,2,opt,name=identityKey,proto3" json:"identityKey,omitempty"`
	IdentityKeySignature []byte   `protobuf:"bytes,3,opt,name=identityKeySignature,proto3" json:"identityKeySignature,omitempty"`
	TimeStamp            int64    `protobuf:"varint,4,opt,name=timeStamp" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreKey) Reset()         { *m = PreKey{} }
func (m *PreKey) String() string { return proto.CompactTextString(m) }
func (*PreKey) ProtoMessage()    {}
func (*PreKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{3}
}
func (m *PreKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreKey.Unmarshal(m, b)
}
func (m *PreKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreKey.Marshal(b, m, deterministic)
}
func (dst *PreKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreKey.Merge(dst, src)
}
func (m *PreKey) XXX_Size() int {
	return xxx_messageInfo_PreKey.Size(m)
}
func (m *PreKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PreKey.DiscardUnknown(m)
}

var xxx_messageInfo_PreKey proto.InternalMessageInfo

func (m *PreKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PreKey) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *PreKey) GetIdentityKeySignature() []byte {
	if m != nil {
		return m.IdentityKeySignature
	}
	return nil
}

func (m *PreKey) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type PreKeyBundle struct {
	PreKey               *PreKey  `protobuf:"bytes,2,opt,name=preKey" json:"preKey,omitempty"`
	OneTimePreKey        *PreKey  `protobuf:"bytes,3,opt,name=oneTimePreKey" json:"oneTimePreKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreKeyBundle) Reset()         { *m = PreKeyBundle{} }
func (m *PreKeyBundle) String() string { return proto.CompactTextString(m) }
func (*PreKeyBundle) ProtoMessage()    {}
func (*PreKeyBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{4}
}
func (m *PreKeyBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreKeyBundle.Unmarshal(m, b)
}
func (m *PreKeyBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreKeyBundle.Marshal(b, m, deterministic)
}
func (dst *PreKeyBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreKeyBundle.Merge(dst, src)
}
func (m *PreKeyBundle) XXX_Size() int {
	return xxx_messageInfo_PreKeyBundle.Size(m)
}
func (m *PreKeyBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_PreKeyBundle.DiscardUnknown(m)
}

var xxx_messageInfo_PreKeyBundle proto.InternalMessageInfo

func (m *PreKeyBundle) GetPreKey() *PreKey {
	if m != nil {
		return m.PreKey
	}
	return nil
}

func (m *PreKeyBundle) GetOneTimePreKey() *PreKey {
	if m != nil {
		return m.OneTimePreKey
	}
	return nil
}

type MessageStateChange struct {
	NewState             MessageStateChange_NewState `protobuf:"varint,1,opt,name=newState,enum=pangea.MessageStateChange_NewState" json:"newState,omitempty"`
	MessageID            []byte                      `protobuf:"bytes,2,opt,name=messageID,proto3" json:"messageID,omitempty"`
	From                 []byte                      `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	FromSignature        []byte                      `protobuf:"bytes,4,opt,name=fromSignature,proto3" json:"fromSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *MessageStateChange) Reset()         { *m = MessageStateChange{} }
func (m *MessageStateChange) String() string { return proto.CompactTextString(m) }
func (*MessageStateChange) ProtoMessage()    {}
func (*MessageStateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{5}
}
func (m *MessageStateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageStateChange.Unmarshal(m, b)
}
func (m *MessageStateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageStateChange.Marshal(b, m, deterministic)
}
func (dst *MessageStateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageStateChange.Merge(dst, src)
}
func (m *MessageStateChange) XXX_Size() int {
	return xxx_messageInfo_MessageStateChange.Size(m)
}
func (m *MessageStateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageStateChange.DiscardUnknown(m)
}

var xxx_messageInfo_MessageStateChange proto.InternalMessageInfo

func (m *MessageStateChange) GetNewState() MessageStateChange_NewState {
	if m != nil {
		return m.NewState
	}
	return MessageStateChange_SENT
}

func (m *MessageStateChange) GetMessageID() []byte {
	if m != nil {
		return m.MessageID
	}
	return nil
}

func (m *MessageStateChange) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *MessageStateChange) GetFromSignature() []byte {
	if m != nil {
		return m.FromSignature
	}
	return nil
}

type BackendMessage struct {
	Request              *BackendMessage_Request  `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Response             *BackendMessage_Response `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	Error                string                   `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	RequestID            []byte                   `protobuf:"bytes,4,opt,name=requestID,proto3" json:"requestID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BackendMessage) Reset()         { *m = BackendMessage{} }
func (m *BackendMessage) String() string { return proto.CompactTextString(m) }
func (*BackendMessage) ProtoMessage()    {}
func (*BackendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{6}
}
func (m *BackendMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendMessage.Unmarshal(m, b)
}
func (m *BackendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendMessage.Marshal(b, m, deterministic)
}
func (dst *BackendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendMessage.Merge(dst, src)
}
func (m *BackendMessage) XXX_Size() int {
	return xxx_messageInfo_BackendMessage.Size(m)
}
func (m *BackendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BackendMessage proto.InternalMessageInfo

func (m *BackendMessage) GetRequest() *BackendMessage_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *BackendMessage) GetResponse() *BackendMessage_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *BackendMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *BackendMessage) GetRequestID() []byte {
	if m != nil {
		return m.RequestID
	}
	return nil
}

type BackendMessage_Auth struct {
	ToSign               []byte   `protobuf:"bytes,1,opt,name=toSign,proto3" json:"toSign,omitempty"`
	IdentityPublicKey    []byte   `protobuf:"bytes,2,opt,name=identityPublicKey,proto3" json:"identityPublicKey,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendMessage_Auth) Reset()         { *m = BackendMessage_Auth{} }
func (m *BackendMessage_Auth) String() string { return proto.CompactTextString(m) }
func (*BackendMessage_Auth) ProtoMessage()    {}
func (*BackendMessage_Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{6, 0}
}
func (m *BackendMessage_Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendMessage_Auth.Unmarshal(m, b)
}
func (m *BackendMessage_Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendMessage_Auth.Marshal(b, m, deterministic)
}
func (dst *BackendMessage_Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendMessage_Auth.Merge(dst, src)
}
func (m *BackendMessage_Auth) XXX_Size() int {
	return xxx_messageInfo_BackendMessage_Auth.Size(m)
}
func (m *BackendMessage_Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendMessage_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_BackendMessage_Auth proto.InternalMessageInfo

func (m *BackendMessage_Auth) GetToSign() []byte {
	if m != nil {
		return m.ToSign
	}
	return nil
}

func (m *BackendMessage_Auth) GetIdentityPublicKey() []byte {
	if m != nil {
		return m.IdentityPublicKey
	}
	return nil
}

func (m *BackendMessage_Auth) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type BackendMessage_Request struct {
	Messages             []*ChatMessage       `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	MessageStateChange   *MessageStateChange  `protobuf:"bytes,2,opt,name=messageStateChange" json:"messageStateChange,omitempty"`
	PreKey               *PreKey              `protobuf:"bytes,3,opt,name=preKey" json:"preKey,omitempty"`
	NewOneTimePreKeys    uint32               `protobuf:"varint,4,opt,name=newOneTimePreKeys" json:"newOneTimePreKeys,omitempty"`
	PreKeyBundle         []byte               `protobuf:"bytes,5,opt,name=preKeyBundle,proto3" json:"preKeyBundle,omitempty"`
	Auth                 *BackendMessage_Auth `protobuf:"bytes,6,opt,name=auth" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BackendMessage_Request) Reset()         { *m = BackendMessage_Request{} }
func (m *BackendMessage_Request) String() string { return proto.CompactTextString(m) }
func (*BackendMessage_Request) ProtoMessage()    {}
func (*BackendMessage_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{6, 1}
}
func (m *BackendMessage_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendMessage_Request.Unmarshal(m, b)
}
func (m *BackendMessage_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendMessage_Request.Marshal(b, m, deterministic)
}
func (dst *BackendMessage_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendMessage_Request.Merge(dst, src)
}
func (m *BackendMessage_Request) XXX_Size() int {
	return xxx_messageInfo_BackendMessage_Request.Size(m)
}
func (m *BackendMessage_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendMessage_Request.DiscardUnknown(m)
}

var xxx_messageInfo_BackendMessage_Request proto.InternalMessageInfo

func (m *BackendMessage_Request) GetMessages() []*ChatMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *BackendMessage_Request) GetMessageStateChange() *MessageStateChange {
	if m != nil {
		return m.MessageStateChange
	}
	return nil
}

func (m *BackendMessage_Request) GetPreKey() *PreKey {
	if m != nil {
		return m.PreKey
	}
	return nil
}

func (m *BackendMessage_Request) GetNewOneTimePreKeys() uint32 {
	if m != nil {
		return m.NewOneTimePreKeys
	}
	return 0
}

func (m *BackendMessage_Request) GetPreKeyBundle() []byte {
	if m != nil {
		return m.PreKeyBundle
	}
	return nil
}

func (m *BackendMessage_Request) GetAuth() *BackendMessage_Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type BackendMessage_Response struct {
	PreKeyBundle         *BackendMessage_PreKeyBundle `protobuf:"bytes,1,opt,name=preKeyBundle" json:"preKeyBundle,omitempty"`
	OneTimePrekeys       []*PreKey                    `protobuf:"bytes,2,rep,name=oneTimePrekeys" json:"oneTimePrekeys,omitempty"`
	Auth                 *BackendMessage_Auth         `protobuf:"bytes,3,opt,name=auth" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *BackendMessage_Response) Reset()         { *m = BackendMessage_Response{} }
func (m *BackendMessage_Response) String() string { return proto.CompactTextString(m) }
func (*BackendMessage_Response) ProtoMessage()    {}
func (*BackendMessage_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{6, 2}
}
func (m *BackendMessage_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendMessage_Response.Unmarshal(m, b)
}
func (m *BackendMessage_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendMessage_Response.Marshal(b, m, deterministic)
}
func (dst *BackendMessage_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendMessage_Response.Merge(dst, src)
}
func (m *BackendMessage_Response) XXX_Size() int {
	return xxx_messageInfo_BackendMessage_Response.Size(m)
}
func (m *BackendMessage_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendMessage_Response.DiscardUnknown(m)
}

var xxx_messageInfo_BackendMessage_Response proto.InternalMessageInfo

func (m *BackendMessage_Response) GetPreKeyBundle() *BackendMessage_PreKeyBundle {
	if m != nil {
		return m.PreKeyBundle
	}
	return nil
}

func (m *BackendMessage_Response) GetOneTimePrekeys() []*PreKey {
	if m != nil {
		return m.OneTimePrekeys
	}
	return nil
}

func (m *BackendMessage_Response) GetAuth() *BackendMessage_Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type BackendMessage_PreKeyBundle struct {
	Profile              *Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
	SignedPreKey         *PreKey  `protobuf:"bytes,2,opt,name=signedPreKey" json:"signedPreKey,omitempty"`
	OneTimePreKey        *PreKey  `protobuf:"bytes,3,opt,name=oneTimePreKey" json:"oneTimePreKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendMessage_PreKeyBundle) Reset()         { *m = BackendMessage_PreKeyBundle{} }
func (m *BackendMessage_PreKeyBundle) String() string { return proto.CompactTextString(m) }
func (*BackendMessage_PreKeyBundle) ProtoMessage()    {}
func (*BackendMessage_PreKeyBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_d08537e132987f0a, []int{6, 3}
}
func (m *BackendMessage_PreKeyBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendMessage_PreKeyBundle.Unmarshal(m, b)
}
func (m *BackendMessage_PreKeyBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendMessage_PreKeyBundle.Marshal(b, m, deterministic)
}
func (dst *BackendMessage_PreKeyBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendMessage_PreKeyBundle.Merge(dst, src)
}
func (m *BackendMessage_PreKeyBundle) XXX_Size() int {
	return xxx_messageInfo_BackendMessage_PreKeyBundle.Size(m)
}
func (m *BackendMessage_PreKeyBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendMessage_PreKeyBundle.DiscardUnknown(m)
}

var xxx_messageInfo_BackendMessage_PreKeyBundle proto.InternalMessageInfo

func (m *BackendMessage_PreKeyBundle) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *BackendMessage_PreKeyBundle) GetSignedPreKey() *PreKey {
	if m != nil {
		return m.SignedPreKey
	}
	return nil
}

func (m *BackendMessage_PreKeyBundle) GetOneTimePreKey() *PreKey {
	if m != nil {
		return m.OneTimePreKey
	}
	return nil
}

func init() {
	proto.RegisterType((*DoubleRatchedMsg)(nil), "pangea.DoubleRatchedMsg")
	proto.RegisterType((*PlainChatMessage)(nil), "pangea.PlainChatMessage")
	proto.RegisterType((*ChatMessage)(nil), "pangea.ChatMessage")
	proto.RegisterType((*PreKey)(nil), "pangea.PreKey")
	proto.RegisterType((*PreKeyBundle)(nil), "pangea.PreKeyBundle")
	proto.RegisterType((*MessageStateChange)(nil), "pangea.MessageStateChange")
	proto.RegisterType((*BackendMessage)(nil), "pangea.BackendMessage")
	proto.RegisterType((*BackendMessage_Auth)(nil), "pangea.BackendMessage.Auth")
	proto.RegisterType((*BackendMessage_Request)(nil), "pangea.BackendMessage.Request")
	proto.RegisterType((*BackendMessage_Response)(nil), "pangea.BackendMessage.Response")
	proto.RegisterType((*BackendMessage_PreKeyBundle)(nil), "pangea.BackendMessage.PreKeyBundle")
	proto.RegisterEnum("pangea.MessageStateChange_NewState", MessageStateChange_NewState_name, MessageStateChange_NewState_value)
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_chat_d08537e132987f0a) }

var fileDescriptor_chat_d08537e132987f0a = []byte{
	// 935 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x8e, 0x1b, 0x45,
	0x10, 0x65, 0x6c, 0xaf, 0x2f, 0xe5, 0x4b, 0x9c, 0x62, 0x41, 0x23, 0x83, 0x82, 0xe5, 0x20, 0x64,
	0x50, 0xe4, 0x48, 0x26, 0x42, 0x5c, 0x1e, 0x90, 0x77, 0x6d, 0xc0, 0x64, 0xb3, 0x59, 0xb5, 0x57,
	0xbc, 0x46, 0xbd, 0x9e, 0x8a, 0x67, 0x58, 0x7b, 0x66, 0xe8, 0x69, 0x27, 0x2c, 0x1f, 0xc1, 0x4f,
	0xf0, 0x05, 0xbc, 0xf3, 0x90, 0x7f, 0xe1, 0x85, 0xcf, 0x40, 0xdd, 0xd3, 0xe3, 0xb9, 0xd8, 0x46,
	0x28, 0x4f, 0x3b, 0x75, 0xea, 0x74, 0x57, 0xd7, 0xa9, 0xd3, 0xed, 0x05, 0x58, 0xba, 0x5c, 0x8e,
	0x42, 0x11, 0xc8, 0x00, 0xab, 0x21, 0xf7, 0x57, 0xc4, 0x7b, 0xad, 0xf8, 0x6f, 0x8c, 0x0e, 0x7e,
	0x83, 0xee, 0x34, 0xd8, 0xde, 0xac, 0x89, 0x71, 0xb9, 0x74, 0xc9, 0x79, 0x16, 0xad, 0x70, 0x08,
	0xf7, 0x9c, 0x0c, 0x26, 0xaf, 0x9e, 0xda, 0x56, 0xdf, 0x1a, 0xb6, 0x58, 0x11, 0xc6, 0x16, 0x58,
	0xbe, 0x5d, 0xea, 0x5b, 0xc3, 0x36, 0xb3, 0x7c, 0xec, 0x40, 0x29, 0xf4, 0xed, 0xb2, 0x0e, 0x4b,
	0xa1, 0x8f, 0x0f, 0x00, 0x96, 0x5e, 0xe8, 0x92, 0xb8, 0xa6, 0x5f, 0xa5, 0x5d, 0xd1, 0x5b, 0x64,
	0x90, 0xc1, 0x9b, 0x12, 0x74, 0xaf, 0xd6, 0xdc, 0xf3, 0xcf, 0x5d, 0x2e, 0x9f, 0x51, 0x14, 0xf1,
	0x15, 0xe1, 0xc7, 0xd0, 0x76, 0x26, 0x61, 0x78, 0xb5, 0xbd, 0x59, 0x7b, 0xcb, 0xa7, 0x74, 0x67,
	0x4a, 0xe7, 0x41, 0x44, 0xa8, 0xc8, 0xbb, 0x90, 0x74, 0xed, 0x06, 0xd3, 0xdf, 0xf8, 0x3e, 0x54,
	0x43, 0x2e, 0xf8, 0x26, 0xd2, 0x47, 0x68, 0x31, 0x13, 0xa1, 0x0d, 0xb5, 0x4d, 0xbc, 0xb9, 0x39,
	0x43, 0x12, 0xe2, 0x87, 0xd0, 0x58, 0x0a, 0xe2, 0x92, 0x9c, 0x89, 0xb4, 0x4f, 0xfa, 0xd6, 0xb0,
	0xcc, 0x52, 0x40, 0x65, 0x0d, 0x71, 0x3e, 0xb5, 0xab, 0xba, 0x50, 0x0a, 0xe0, 0x08, 0x30, 0x72,
	0xb9, 0x20, 0x67, 0x41, 0x4b, 0x41, 0xf2, 0x8c, 0x47, 0x8a, 0x56, 0xd3, 0x05, 0x0e, 0x64, 0xf0,
	0x6b, 0xb0, 0xb3, 0xe8, 0xb9, 0x2a, 0xe3, 0x05, 0xfe, 0x94, 0x4b, 0xb2, 0xeb, 0xba, 0xf4, 0xd1,
	0xbc, 0xea, 0xe0, 0x15, 0x89, 0xc8, 0x0b, 0x7c, 0xbb, 0xa1, 0xd5, 0x4d, 0xc2, 0xc1, 0xdf, 0x65,
	0x68, 0x16, 0xd4, 0x0b, 0x7c, 0xba, 0xf6, 0x36, 0x74, 0x25, 0x28, 0xa3, 0x5e, 0x0e, 0xc4, 0x01,
	0xb4, 0x22, 0x6f, 0xe5, 0x93, 0x63, 0x48, 0x25, 0x4d, 0xca, 0x61, 0x8a, 0x43, 0xa1, 0x4b, 0x1b,
	0x12, 0x7c, 0xad, 0x38, 0xb1, 0xa6, 0x39, 0x0c, 0x9f, 0xc0, 0x7b, 0xd9, 0x78, 0xe1, 0xad, 0x7c,
	0x2e, 0xb7, 0x22, 0xd1, 0xf9, 0x70, 0x52, 0xd9, 0x2b, 0x22, 0xdf, 0x21, 0xa1, 0x0e, 0x3e, 0x9f,
	0xaa, 0xcd, 0x4f, 0x62, 0x7b, 0x15, 0x60, 0xad, 0x59, 0x1e, 0x4a, 0x4b, 0x54, 0xf5, 0x92, 0xa3,
	0x79, 0x1c, 0xa7, 0x53, 0x57, 0xf2, 0x36, 0xc7, 0xf6, 0xc8, 0x18, 0xbf, 0xe8, 0xf7, 0xd4, 0x0f,
	0x3d, 0xa8, 0x0b, 0x5a, 0x92, 0xf7, 0x8a, 0x84, 0x16, 0xba, 0xc5, 0x76, 0xb1, 0x72, 0x57, 0x5c,
	0xcb, 0x86, 0xd8, 0x5d, 0x71, 0x94, 0x77, 0x49, 0x53, 0xa7, 0x32, 0x2e, 0xf9, 0x0c, 0xba, 0xdb,
	0x88, 0x9c, 0x45, 0x66, 0xb2, 0x76, 0x4b, 0x93, 0xf6, 0xf0, 0xec, 0x94, 0xdb, 0xf9, 0x29, 0xff,
	0x6e, 0x41, 0xd5, 0x8c, 0xa5, 0x0b, 0xe5, 0xdb, 0xdd, 0x58, 0xd5, 0x27, 0xf6, 0xa1, 0xe9, 0x39,
	0xe4, 0x4b, 0x4f, 0xde, 0xa5, 0xb3, 0xcc, 0x42, 0x38, 0x86, 0xd3, 0x4c, 0x98, 0x4a, 0x18, 0x8f,
	0xf4, 0x60, 0x4e, 0xb5, 0x25, 0xbd, 0x0d, 0x2d, 0x24, 0xdf, 0x84, 0x7a, 0x9c, 0x65, 0x96, 0x02,
	0x83, 0x35, 0xb4, 0xe2, 0xf3, 0x9c, 0x6d, 0x7d, 0x67, 0x4d, 0xf8, 0x09, 0x54, 0xc3, 0xd4, 0x4a,
	0xcd, 0x71, 0x27, 0xd1, 0x3a, 0x66, 0x31, 0x93, 0xc5, 0x27, 0x45, 0x7b, 0x96, 0x0f, 0xd2, 0xf3,
	0xa4, 0xc1, 0x3f, 0x16, 0xa0, 0x31, 0xf8, 0x42, 0x72, 0x49, 0xe7, 0xae, 0x62, 0xe3, 0xb7, 0x50,
	0xf7, 0xe9, 0xb5, 0x46, 0xb4, 0x1e, 0x9d, 0xf1, 0xc3, 0x64, 0x9f, 0x7d, 0xf6, 0xe8, 0xd2, 0x50,
	0xd9, 0x6e, 0x51, 0x7e, 0x74, 0xa5, 0xe2, 0xe8, 0x10, 0x2a, 0x2f, 0x45, 0xb0, 0x31, 0x2a, 0xe9,
	0x6f, 0x75, 0xbd, 0xd4, 0xdf, 0xa2, 0xd1, 0xf3, 0xe0, 0xe0, 0x2b, 0xa8, 0x27, 0xd5, 0xb0, 0x0e,
	0x95, 0xc5, 0xec, 0xf2, 0xba, 0xfb, 0x0e, 0xb6, 0xa1, 0x31, 0x9d, 0x5d, 0xcc, 0x7f, 0x9a, 0xb1,
	0xd9, 0xb4, 0x6b, 0xe1, 0x29, 0x74, 0xbf, 0x9b, 0xcc, 0x2f, 0x66, 0xd3, 0x17, 0xd7, 0xcf, 0x5f,
	0xfc, 0x30, 0xb9, 0x9c, 0x5e, 0xcc, 0xba, 0xa5, 0xc1, 0x9b, 0x1a, 0x74, 0xce, 0xf8, 0xf2, 0x96,
	0x7c, 0x27, 0xb9, 0xd2, 0x5f, 0x42, 0x4d, 0xd0, 0x2f, 0x5b, 0x8a, 0xa4, 0xee, 0xb2, 0x39, 0x7e,
	0x90, 0x74, 0x99, 0x27, 0x8e, 0x58, 0xcc, 0x62, 0x09, 0x1d, 0xbf, 0x51, 0x76, 0x8e, 0xc2, 0xc0,
	0x8f, 0xc8, 0xcc, 0xe5, 0xa3, 0xa3, 0x4b, 0x63, 0x1a, 0xdb, 0x2d, 0xc0, 0x53, 0x38, 0x21, 0x21,
	0x02, 0xa1, 0xfb, 0x6f, 0xb0, 0x38, 0x50, 0x92, 0x99, 0xdd, 0xe7, 0x53, 0xd3, 0x7c, 0x0a, 0xf4,
	0x7e, 0x86, 0xca, 0x64, 0x2b, 0x5d, 0x75, 0x57, 0x64, 0xa0, 0xf4, 0x30, 0x3e, 0x35, 0x11, 0x3e,
	0x82, 0xfb, 0x89, 0xd9, 0xd2, 0xf7, 0x3d, 0x16, 0x7e, 0x3f, 0xa1, 0x6a, 0x45, 0x05, 0xaf, 0xa6,
	0x40, 0xef, 0xcf, 0x12, 0xd4, 0x4c, 0xc7, 0xf8, 0x18, 0xea, 0x66, 0x6e, 0x91, 0x6d, 0xf5, 0xcb,
	0xc3, 0xe6, 0xf8, 0xdd, 0xa4, 0xd1, 0xcc, 0xe3, 0xc8, 0x76, 0x24, 0xfc, 0x11, 0x70, 0xb3, 0x67,
	0x11, 0xa3, 0x51, 0xef, 0xb8, 0x89, 0xd8, 0x81, 0x55, 0x19, 0xef, 0x97, 0xff, 0xd3, 0xfb, 0x8f,
	0xe0, 0xbe, 0x4f, 0xaf, 0x9f, 0x67, 0x9d, 0x1d, 0x69, 0x09, 0xdb, 0x6c, 0x3f, 0xa1, 0x9e, 0xdf,
	0x30, 0x73, 0xc3, 0xcc, 0x0b, 0x99, 0xc3, 0xf0, 0x31, 0x54, 0xf8, 0x56, 0xba, 0xfa, 0x29, 0x6c,
	0x8e, 0x3f, 0x38, 0x32, 0x5b, 0x35, 0x11, 0xa6, 0x89, 0xbd, 0xbf, 0x2c, 0xa8, 0x27, 0xa3, 0xc6,
	0xef, 0x0b, 0x15, 0x62, 0x73, 0x3d, 0x3c, 0xb2, 0x4b, 0xf6, 0xba, 0x17, 0x8e, 0xf1, 0x05, 0x74,
	0xd2, 0xfb, 0x7a, 0xab, 0xba, 0x2a, 0xe9, 0x19, 0x14, 0x85, 0x28, 0xb0, 0x76, 0xc7, 0x2f, 0xff,
	0xdf, 0xe3, 0xff, 0x61, 0x15, 0x9e, 0x9d, 0x4f, 0xa1, 0x16, 0x8a, 0xe0, 0xa5, 0xb7, 0x3b, 0xfd,
	0xbd, 0xb4, 0xa4, 0x86, 0x59, 0x92, 0xc7, 0xf1, 0x81, 0x9f, 0xbc, 0xfd, 0x23, 0xe6, 0x7f, 0x02,
	0xdf, 0xea, 0xb5, 0xba, 0xa9, 0xea, 0x7f, 0xac, 0x3e, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe7,
	0x85, 0x4c, 0x63, 0x7c, 0x09, 0x00, 0x00,
}
