// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package pangea

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageStateChange_NewState int32

const (
	MessageStateChange_SENT             MessageStateChange_NewState = 0
	MessageStateChange_DELIVERED        MessageStateChange_NewState = 1
	MessageStateChange_FAILED_TO_HANDLE MessageStateChange_NewState = 2
)

var MessageStateChange_NewState_name = map[int32]string{
	0: "SENT",
	1: "DELIVERED",
	2: "FAILED_TO_HANDLE",
}
var MessageStateChange_NewState_value = map[string]int32{
	"SENT":             0,
	"DELIVERED":        1,
	"FAILED_TO_HANDLE": 2,
}

func (x MessageStateChange_NewState) String() string {
	return proto.EnumName(MessageStateChange_NewState_name, int32(x))
}
func (MessageStateChange_NewState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chat_c395f2465a6e437e, []int{5, 0}
}

type DoubleRatchedMsg struct {
	DoubleRatchetPK      []byte   `protobuf:"bytes,1,opt,name=doubleRatchetPK,proto3" json:"doubleRatchetPK,omitempty"`
	N                    uint32   `protobuf:"varint,2,opt,name=n" json:"n,omitempty"`
	Pn                   uint32   `protobuf:"varint,3,opt,name=pn" json:"pn,omitempty"`
	CipherText           []byte   `protobuf:"bytes,4,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleRatchedMsg) Reset()         { *m = DoubleRatchedMsg{} }
func (m *DoubleRatchedMsg) String() string { return proto.CompactTextString(m) }
func (*DoubleRatchedMsg) ProtoMessage()    {}
func (*DoubleRatchedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c395f2465a6e437e, []int{0}
}
func (m *DoubleRatchedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleRatchedMsg.Unmarshal(m, b)
}
func (m *DoubleRatchedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleRatchedMsg.Marshal(b, m, deterministic)
}
func (dst *DoubleRatchedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleRatchedMsg.Merge(dst, src)
}
func (m *DoubleRatchedMsg) XXX_Size() int {
	return xxx_messageInfo_DoubleRatchedMsg.Size(m)
}
func (m *DoubleRatchedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleRatchedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleRatchedMsg proto.InternalMessageInfo

func (m *DoubleRatchedMsg) GetDoubleRatchetPK() []byte {
	if m != nil {
		return m.DoubleRatchetPK
	}
	return nil
}

func (m *DoubleRatchedMsg) GetN() uint32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *DoubleRatchedMsg) GetPn() uint32 {
	if m != nil {
		return m.Pn
	}
	return 0
}

func (m *DoubleRatchedMsg) GetCipherText() []byte {
	if m != nil {
		return m.CipherText
	}
	return nil
}

type PlainChatMessage struct {
	DAppPublicKey        []byte   `protobuf:"bytes,1,opt,name=dAppPublicKey,proto3" json:"dAppPublicKey,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Params               []byte   `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	Message              []byte   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=createdAt" json:"createdAt,omitempty"`
	MessageID            string   `protobuf:"bytes,6,opt,name=messageID" json:"messageID,omitempty"`
	SharedSecretID       []byte   `protobuf:"bytes,7,opt,name=sharedSecretID,proto3" json:"sharedSecretID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlainChatMessage) Reset()         { *m = PlainChatMessage{} }
func (m *PlainChatMessage) String() string { return proto.CompactTextString(m) }
func (*PlainChatMessage) ProtoMessage()    {}
func (*PlainChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c395f2465a6e437e, []int{1}
}
func (m *PlainChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlainChatMessage.Unmarshal(m, b)
}
func (m *PlainChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlainChatMessage.Marshal(b, m, deterministic)
}
func (dst *PlainChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlainChatMessage.Merge(dst, src)
}
func (m *PlainChatMessage) XXX_Size() int {
	return xxx_messageInfo_PlainChatMessage.Size(m)
}
func (m *PlainChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PlainChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PlainChatMessage proto.InternalMessageInfo

func (m *PlainChatMessage) GetDAppPublicKey() []byte {
	if m != nil {
		return m.DAppPublicKey
	}
	return nil
}

func (m *PlainChatMessage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PlainChatMessage) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *PlainChatMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PlainChatMessage) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *PlainChatMessage) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *PlainChatMessage) GetSharedSecretID() []byte {
	if m != nil {
		return m.SharedSecretID
	}
	return nil
}

type ChatMessage struct {
	OneTimePreKey            []byte            `protobuf:"bytes,1,opt,name=oneTimePreKey,proto3" json:"oneTimePreKey,omitempty"`
	SignedPreKey             []byte            `protobuf:"bytes,2,opt,name=signedPreKey,proto3" json:"signedPreKey,omitempty"`
	EphemeralKey             []byte            `protobuf:"bytes,3,opt,name=ephemeralKey,proto3" json:"ephemeralKey,omitempty"`
	EphemeralKeySignature    []byte            `protobuf:"bytes,4,opt,name=ephemeralKeySignature,proto3" json:"ephemeralKeySignature,omitempty"`
	SenderChatIDKey          []byte            `protobuf:"bytes,5,opt,name=senderChatIDKey,proto3" json:"senderChatIDKey,omitempty"`
	SenderChatIDKeySignature []byte            `protobuf:"bytes,6,opt,name=senderChatIDKeySignature,proto3" json:"senderChatIDKeySignature,omitempty"`
	SharedSecretCreationDate int64             `protobuf:"varint,7,opt,name=sharedSecretCreationDate" json:"sharedSecretCreationDate,omitempty"`
	Message                  *DoubleRatchedMsg `protobuf:"bytes,8,opt,name=message" json:"message,omitempty"`
	Receiver                 []byte            `protobuf:"bytes,9,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender                   []byte            `protobuf:"bytes,10,opt,name=sender,proto3" json:"sender,omitempty"`
	MessageID                []byte            `protobuf:"bytes,11,opt,name=messageID,proto3" json:"messageID,omitempty"`
	UsedSharedSecret         []byte            `protobuf:"bytes,12,opt,name=usedSharedSecret,proto3" json:"usedSharedSecret,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}          `json:"-"`
	XXX_unrecognized         []byte            `json:"-"`
	XXX_sizecache            int32             `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c395f2465a6e437e, []int{2}
}
func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (dst *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(dst, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetOneTimePreKey() []byte {
	if m != nil {
		return m.OneTimePreKey
	}
	return nil
}

func (m *ChatMessage) GetSignedPreKey() []byte {
	if m != nil {
		return m.SignedPreKey
	}
	return nil
}

func (m *ChatMessage) GetEphemeralKey() []byte {
	if m != nil {
		return m.EphemeralKey
	}
	return nil
}

func (m *ChatMessage) GetEphemeralKeySignature() []byte {
	if m != nil {
		return m.EphemeralKeySignature
	}
	return nil
}

func (m *ChatMessage) GetSenderChatIDKey() []byte {
	if m != nil {
		return m.SenderChatIDKey
	}
	return nil
}

func (m *ChatMessage) GetSenderChatIDKeySignature() []byte {
	if m != nil {
		return m.SenderChatIDKeySignature
	}
	return nil
}

func (m *ChatMessage) GetSharedSecretCreationDate() int64 {
	if m != nil {
		return m.SharedSecretCreationDate
	}
	return 0
}

func (m *ChatMessage) GetMessage() *DoubleRatchedMsg {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ChatMessage) GetReceiver() []byte {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *ChatMessage) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *ChatMessage) GetMessageID() []byte {
	if m != nil {
		return m.MessageID
	}
	return nil
}

func (m *ChatMessage) GetUsedSharedSecret() []byte {
	if m != nil {
		return m.UsedSharedSecret
	}
	return nil
}

type PreKey struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	IdentityKey          []byte   `protobuf:"bytes,2,opt,name=identityKey,proto3" json:"identityKey,omitempty"`
	IdentityKeySignature []byte   `protobuf:"bytes,3,opt,name=identityKeySignature,proto3" json:"identityKeySignature,omitempty"`
	TimeStamp            int64    `protobuf:"varint,4,opt,name=timeStamp" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreKey) Reset()         { *m = PreKey{} }
func (m *PreKey) String() string { return proto.CompactTextString(m) }
func (*PreKey) ProtoMessage()    {}
func (*PreKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c395f2465a6e437e, []int{3}
}
func (m *PreKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreKey.Unmarshal(m, b)
}
func (m *PreKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreKey.Marshal(b, m, deterministic)
}
func (dst *PreKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreKey.Merge(dst, src)
}
func (m *PreKey) XXX_Size() int {
	return xxx_messageInfo_PreKey.Size(m)
}
func (m *PreKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PreKey.DiscardUnknown(m)
}

var xxx_messageInfo_PreKey proto.InternalMessageInfo

func (m *PreKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PreKey) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *PreKey) GetIdentityKeySignature() []byte {
	if m != nil {
		return m.IdentityKeySignature
	}
	return nil
}

func (m *PreKey) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type PreKeyBundle struct {
	PreKey               *PreKey  `protobuf:"bytes,2,opt,name=preKey" json:"preKey,omitempty"`
	OneTimePreKey        *PreKey  `protobuf:"bytes,3,opt,name=oneTimePreKey" json:"oneTimePreKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreKeyBundle) Reset()         { *m = PreKeyBundle{} }
func (m *PreKeyBundle) String() string { return proto.CompactTextString(m) }
func (*PreKeyBundle) ProtoMessage()    {}
func (*PreKeyBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c395f2465a6e437e, []int{4}
}
func (m *PreKeyBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreKeyBundle.Unmarshal(m, b)
}
func (m *PreKeyBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreKeyBundle.Marshal(b, m, deterministic)
}
func (dst *PreKeyBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreKeyBundle.Merge(dst, src)
}
func (m *PreKeyBundle) XXX_Size() int {
	return xxx_messageInfo_PreKeyBundle.Size(m)
}
func (m *PreKeyBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_PreKeyBundle.DiscardUnknown(m)
}

var xxx_messageInfo_PreKeyBundle proto.InternalMessageInfo

func (m *PreKeyBundle) GetPreKey() *PreKey {
	if m != nil {
		return m.PreKey
	}
	return nil
}

func (m *PreKeyBundle) GetOneTimePreKey() *PreKey {
	if m != nil {
		return m.OneTimePreKey
	}
	return nil
}

type MessageStateChange struct {
	NewState             MessageStateChange_NewState `protobuf:"varint,1,opt,name=newState,enum=pangea.MessageStateChange_NewState" json:"newState,omitempty"`
	MessageID            []byte                      `protobuf:"bytes,2,opt,name=messageID,proto3" json:"messageID,omitempty"`
	From                 []byte                      `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	FromSignature        []byte                      `protobuf:"bytes,4,opt,name=fromSignature,proto3" json:"fromSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *MessageStateChange) Reset()         { *m = MessageStateChange{} }
func (m *MessageStateChange) String() string { return proto.CompactTextString(m) }
func (*MessageStateChange) ProtoMessage()    {}
func (*MessageStateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_c395f2465a6e437e, []int{5}
}
func (m *MessageStateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageStateChange.Unmarshal(m, b)
}
func (m *MessageStateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageStateChange.Marshal(b, m, deterministic)
}
func (dst *MessageStateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageStateChange.Merge(dst, src)
}
func (m *MessageStateChange) XXX_Size() int {
	return xxx_messageInfo_MessageStateChange.Size(m)
}
func (m *MessageStateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageStateChange.DiscardUnknown(m)
}

var xxx_messageInfo_MessageStateChange proto.InternalMessageInfo

func (m *MessageStateChange) GetNewState() MessageStateChange_NewState {
	if m != nil {
		return m.NewState
	}
	return MessageStateChange_SENT
}

func (m *MessageStateChange) GetMessageID() []byte {
	if m != nil {
		return m.MessageID
	}
	return nil
}

func (m *MessageStateChange) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *MessageStateChange) GetFromSignature() []byte {
	if m != nil {
		return m.FromSignature
	}
	return nil
}

func init() {
	proto.RegisterType((*DoubleRatchedMsg)(nil), "pangea.DoubleRatchedMsg")
	proto.RegisterType((*PlainChatMessage)(nil), "pangea.PlainChatMessage")
	proto.RegisterType((*ChatMessage)(nil), "pangea.ChatMessage")
	proto.RegisterType((*PreKey)(nil), "pangea.PreKey")
	proto.RegisterType((*PreKeyBundle)(nil), "pangea.PreKeyBundle")
	proto.RegisterType((*MessageStateChange)(nil), "pangea.MessageStateChange")
	proto.RegisterEnum("pangea.MessageStateChange_NewState", MessageStateChange_NewState_name, MessageStateChange_NewState_value)
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_chat_c395f2465a6e437e) }

var fileDescriptor_chat_c395f2465a6e437e = []byte{
	// 629 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x49, 0xea, 0x26, 0x93, 0x34, 0x58, 0xa3, 0x82, 0x2c, 0x84, 0x50, 0x64, 0x50, 0x15,
	0x71, 0xc8, 0x21, 0xf4, 0x02, 0x17, 0x14, 0xea, 0x20, 0xa2, 0x7e, 0x10, 0x39, 0x11, 0xd7, 0x6a,
	0x6b, 0x0f, 0xb1, 0x45, 0xbc, 0xb1, 0xd6, 0x1b, 0xa0, 0xdc, 0xb9, 0xf2, 0x23, 0x39, 0xf1, 0x33,
	0xd0, 0xae, 0x9d, 0xfa, 0xa3, 0xe9, 0x29, 0x9e, 0x37, 0x6f, 0x67, 0x66, 0xe7, 0xbd, 0x0d, 0x80,
	0x1f, 0x32, 0x39, 0x4a, 0xc4, 0x46, 0x6e, 0xd0, 0x4c, 0x18, 0x5f, 0x11, 0x73, 0x7e, 0x81, 0xe5,
	0x6e, 0xb6, 0x37, 0x6b, 0xf2, 0x98, 0xf4, 0x43, 0x0a, 0x2e, 0xd3, 0x15, 0x0e, 0xe1, 0x71, 0x50,
	0xc2, 0xe4, 0xfc, 0xdc, 0x36, 0x06, 0xc6, 0xb0, 0xe7, 0xd5, 0x61, 0xec, 0x81, 0xc1, 0xed, 0xc6,
	0xc0, 0x18, 0x1e, 0x79, 0x06, 0xc7, 0x3e, 0x34, 0x12, 0x6e, 0x37, 0x75, 0xd8, 0x48, 0x38, 0xbe,
	0x00, 0xf0, 0xa3, 0x24, 0x24, 0xb1, 0xa4, 0x9f, 0xd2, 0x6e, 0xe9, 0x12, 0x25, 0xc4, 0xf9, 0x6b,
	0x80, 0x35, 0x5f, 0xb3, 0x88, 0x9f, 0x85, 0x4c, 0x5e, 0x52, 0x9a, 0xb2, 0x15, 0xe1, 0x2b, 0x38,
	0x0a, 0x26, 0x49, 0x32, 0xdf, 0xde, 0xac, 0x23, 0xff, 0x9c, 0x6e, 0xf3, 0xd6, 0x55, 0x10, 0x11,
	0x5a, 0xf2, 0x36, 0x21, 0xdd, 0xbb, 0xe3, 0xe9, 0x6f, 0x7c, 0x0a, 0x66, 0xc2, 0x04, 0x8b, 0x53,
	0x3d, 0x42, 0xcf, 0xcb, 0x23, 0xb4, 0xe1, 0x30, 0xce, 0x8a, 0xe7, 0x33, 0xec, 0x42, 0x7c, 0x0e,
	0x1d, 0x5f, 0x10, 0x93, 0x14, 0x4c, 0xa4, 0x7d, 0x30, 0x30, 0x86, 0x4d, 0xaf, 0x00, 0x54, 0x36,
	0x27, 0xce, 0x5c, 0xdb, 0xd4, 0x8d, 0x0a, 0x00, 0x4f, 0xa0, 0x9f, 0x86, 0x4c, 0x50, 0xb0, 0x20,
	0x5f, 0x90, 0x9c, 0xb9, 0xf6, 0xa1, 0x2e, 0x5e, 0x43, 0x9d, 0xdf, 0x2d, 0xe8, 0xd6, 0xee, 0xb7,
	0xe1, 0xb4, 0x8c, 0x62, 0x9a, 0x0b, 0x2a, 0xdd, 0xaf, 0x02, 0xa2, 0x03, 0xbd, 0x34, 0x5a, 0x71,
	0x0a, 0x72, 0x52, 0x43, 0x93, 0x2a, 0x98, 0xe2, 0x50, 0x12, 0x52, 0x4c, 0x82, 0xad, 0x15, 0x27,
	0xbb, 0x75, 0x05, 0xc3, 0x53, 0x78, 0x52, 0x8e, 0x17, 0xd1, 0x8a, 0x33, 0xb9, 0x15, 0xbb, 0x4d,
	0xec, 0x4f, 0x2a, 0x03, 0xa4, 0xc4, 0x03, 0x12, 0x6a, 0xf0, 0x99, 0xab, 0x8a, 0x1f, 0x64, 0x06,
	0xa8, 0xc1, 0xf8, 0x0e, 0xec, 0x1a, 0x54, 0xb4, 0x30, 0xf5, 0x91, 0x07, 0xf3, 0xfa, 0x6c, 0x69,
	0x57, 0x67, 0x6a, 0xf1, 0xd1, 0x86, 0xbb, 0x4c, 0x92, 0xde, 0x65, 0xd3, 0x7b, 0x30, 0x8f, 0xe3,
	0x42, 0xd3, 0xf6, 0xc0, 0x18, 0x76, 0xc7, 0xf6, 0x28, 0x33, 0xf4, 0xa8, 0xee, 0xe6, 0x42, 0xed,
	0x67, 0xd0, 0x16, 0xe4, 0x53, 0xf4, 0x9d, 0x84, 0xdd, 0xd1, 0xb3, 0xdd, 0xc5, 0xca, 0x3b, 0xd9,
	0x9c, 0x36, 0x64, 0xde, 0xc9, 0xa2, 0xaa, 0x07, 0xba, 0x3a, 0x55, 0xf2, 0xc0, 0x6b, 0xb0, 0xb6,
	0x29, 0x05, 0x8b, 0xd2, 0x94, 0x76, 0x4f, 0x93, 0xee, 0xe1, 0xce, 0x1f, 0x03, 0xcc, 0x5c, 0x38,
	0x0b, 0x9a, 0xdf, 0xee, 0x84, 0x57, 0x9f, 0x38, 0x80, 0x6e, 0x14, 0x10, 0x97, 0x91, 0xbc, 0x2d,
	0xd4, 0x2e, 0x43, 0x38, 0x86, 0xe3, 0x52, 0x58, 0x2c, 0x39, 0x13, 0x7d, 0x6f, 0x4e, 0x0d, 0x2f,
	0xa3, 0x98, 0x16, 0x92, 0xc5, 0x89, 0x16, 0xbc, 0xe9, 0x15, 0x80, 0xb3, 0x86, 0x5e, 0x36, 0xcf,
	0x87, 0x2d, 0x0f, 0xd6, 0x84, 0x27, 0x60, 0x26, 0x85, 0xd9, 0xba, 0xe3, 0xfe, 0x6e, 0xa3, 0x19,
	0xcb, 0xcb, 0xb3, 0x78, 0x5a, 0x37, 0x70, 0x73, 0x2f, 0xbd, 0x4a, 0x72, 0xfe, 0x19, 0x80, 0xf9,
	0x13, 0x58, 0x48, 0x26, 0xe9, 0x2c, 0x54, 0x6c, 0x7c, 0x0f, 0x6d, 0x4e, 0x3f, 0x34, 0xa2, 0xf7,
	0xd1, 0x1f, 0xbf, 0xdc, 0xd5, 0xb9, 0xcf, 0x1e, 0x5d, 0xe5, 0x54, 0xef, 0xee, 0x50, 0x55, 0xa0,
	0x46, 0x5d, 0x20, 0x84, 0xd6, 0x57, 0xb1, 0x89, 0xf3, 0x2d, 0xe9, 0x6f, 0xf5, 0x00, 0xd5, 0x6f,
	0xfd, 0x29, 0x54, 0x41, 0xe7, 0x2d, 0xb4, 0x77, 0xdd, 0xb0, 0x0d, 0xad, 0xc5, 0xf4, 0x6a, 0x69,
	0x3d, 0xc2, 0x23, 0xe8, 0xb8, 0xd3, 0x8b, 0xd9, 0x97, 0xa9, 0x37, 0x75, 0x2d, 0x03, 0x8f, 0xc1,
	0xfa, 0x38, 0x99, 0x5d, 0x4c, 0xdd, 0xeb, 0xe5, 0xe7, 0xeb, 0x4f, 0x93, 0x2b, 0xf7, 0x62, 0x6a,
	0x35, 0x6e, 0x4c, 0xfd, 0x0f, 0xfb, 0xe6, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0x96, 0x02,
	0xae, 0x6f, 0x05, 0x00, 0x00,
}
