// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pangea.proto

package pangea

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Profile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	IdentityPubKey       []byte   `protobuf:"bytes,4,opt,name=identityPubKey,proto3" json:"identityPubKey,omitempty"`
	EthereumPubKey       []byte   `protobuf:"bytes,5,opt,name=ethereumPubKey,proto3" json:"ethereumPubKey,omitempty"`
	ChatIdentityPubKey   []byte   `protobuf:"bytes,6,opt,name=chatIdentityPubKey,proto3" json:"chatIdentityPubKey,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version              uint32   `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	IdentityKeySignature []byte   `protobuf:"bytes,9,opt,name=identityKeySignature,proto3" json:"identityKeySignature,omitempty"`
	EthereumKeySignature []byte   `protobuf:"bytes,10,opt,name=ethereumKeySignature,proto3" json:"ethereumKeySignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_pangea_0232f65404b13a12, []int{0}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (dst *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(dst, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Profile) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Profile) GetIdentityPubKey() []byte {
	if m != nil {
		return m.IdentityPubKey
	}
	return nil
}

func (m *Profile) GetEthereumPubKey() []byte {
	if m != nil {
		return m.EthereumPubKey
	}
	return nil
}

func (m *Profile) GetChatIdentityPubKey() []byte {
	if m != nil {
		return m.ChatIdentityPubKey
	}
	return nil
}

func (m *Profile) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Profile) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Profile) GetIdentityKeySignature() []byte {
	if m != nil {
		return m.IdentityKeySignature
	}
	return nil
}

func (m *Profile) GetEthereumKeySignature() []byte {
	if m != nil {
		return m.EthereumKeySignature
	}
	return nil
}

func init() {
	proto.RegisterType((*Profile)(nil), "pangea.Profile")
}

func init() { proto.RegisterFile("pangea.proto", fileDescriptor_pangea_0232f65404b13a12) }

var fileDescriptor_pangea_0232f65404b13a12 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0xfe, 0x24, 0xcd, 0xa8, 0xb0, 0x18, 0x75, 0x61, 0x21, 0x16, 0x11, 0x0b, 0x94,
	0x55, 0x17, 0x70, 0x0a, 0xd4, 0x4d, 0x15, 0x4e, 0x30, 0x2d, 0x43, 0x6a, 0xa9, 0xb6, 0x23, 0x67,
	0x82, 0x94, 0x53, 0x73, 0x05, 0x14, 0x87, 0x80, 0x52, 0x65, 0xe7, 0xf7, 0xde, 0xf7, 0xec, 0xb1,
	0x06, 0xb6, 0x35, 0xb9, 0x8a, 0x69, 0x5f, 0x07, 0x2f, 0x1e, 0x93, 0x41, 0x3d, 0x7d, 0x2f, 0x20,
	0x3d, 0x06, 0xff, 0x69, 0xae, 0x8c, 0x08, 0x2b, 0x47, 0x96, 0xb5, 0xca, 0x55, 0x91, 0x95, 0xf1,
	0x8c, 0x0f, 0xb0, 0xb9, 0xfa, 0x33, 0x89, 0xf1, 0x4e, 0x2f, 0xa2, 0xff, 0xa7, 0x71, 0x07, 0x6b,
	0x63, 0xa9, 0x62, 0xbd, 0x8c, 0xc1, 0x20, 0xf0, 0x19, 0xee, 0xcd, 0x07, 0x3b, 0x31, 0xd2, 0x1d,
	0xdb, 0xd3, 0x81, 0x3b, 0xbd, 0xca, 0x55, 0xb1, 0x2d, 0x6f, 0xdc, 0x9e, 0x63, 0xb9, 0x70, 0xe0,
	0xd6, 0xfe, 0x72, 0xeb, 0x81, 0x9b, 0xba, 0xb8, 0x07, 0x3c, 0x5f, 0x48, 0xde, 0xa6, 0x77, 0x26,
	0x91, 0x9d, 0x49, 0xf0, 0x11, 0x32, 0x31, 0x96, 0x1b, 0x21, 0x5b, 0xeb, 0x34, 0x57, 0xc5, 0xb2,
	0xfc, 0x37, 0x50, 0x43, 0xfa, 0xc5, 0xa1, 0xe9, 0xbf, 0xb3, 0xc9, 0x55, 0x71, 0x57, 0x8e, 0x12,
	0x5f, 0x60, 0x37, 0x4e, 0x78, 0xe0, 0xee, 0xdd, 0x54, 0x8e, 0xa4, 0x0d, 0xac, 0xb3, 0xf8, 0xd2,
	0x6c, 0xd6, 0x77, 0xc6, 0x69, 0x27, 0x1d, 0x18, 0x3a, 0x73, 0xd9, 0x29, 0x89, 0x0b, 0x78, 0xfd,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x26, 0x3e, 0xfa, 0x90, 0x01, 0x00, 0x00,
}
